### ISSUE TITLE
Issues sharing user profiles when I deploy on Vercel

### ISSUE THREAD

**Issue by masonc-dev** [nekusu/apetype#45]
Hello, I forked your repository and deployed it to Vercel and Linked it to firebase, everything seems to work fine but when people go to user profiles, www.mydomain.com/user/[name] It gives a server side error:
```
Error: 2 UNKNOWN: Getting metadata from plugin failed with error: error:1E08010C:DECODER routines::unsupported
    at callErrorFromStatus (/var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:357:73)
    at Object.onReceiveStatus (/var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:340:32)
    at ServiceClientImpl.<anonymous> (/var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /var/task/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:227:29
    at /var/task/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:38:28
    at /var/task/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at Object.request (/var/task/node_modules/google-gax/build/src/streamingCalls/streaming.js:130:40)
    at Timeout.makeRequest [as _onTimeout] (/var/task/node_modules/retry-request/index.js:141:28)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Caused by: Error
    at Query._get (/var/task/node_modules/@google-cloud/firestore/build/src/reference.js:1738:23)
    at Query.get (/var/task/node_modules/@google-cloud/firestore/build/src/reference.js:1726:21)
    at getCollection (/var/task/.next/server/chunks/159.js:53:12924)
    at UserPage (/var/task/.next/server/app/user/[id]/page.js:1:4715)
    at /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:111:8442
    at /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:111:8571
    at async rw (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:111:8265)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:111:7294
    at async Promise.all (index 0)
    at async rw (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:111:7063) {
  code: 2,
  details: 'Getting metadata from plugin failed with error: error:1E08010C:DECODER routines::unsupported',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```
My Firebase Firestore rules:
```
rules_version = '2';

service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}
```

**Comment by nekusu** [comment]
Hello, it seems there might be an issue with your Firebase Admin SDK setup. Before proceeding, could you confirm whether the application currently works in a development environment?

If so, please ensure that the environment variables are correctly configured in Vercel. Specifically, for the Admin SDK, you need to provide the `client email` and `private key`.

To troubleshoot, make sure you have followed the setup steps meticulously as outlined in the [Firebase Admin SDK documentation](https://firebase.google.com/docs/admin/setup#initialize_the_sdk_in_non-google_environments).

If you have any further questions, feel free to reach out for assistance.

**Comment by masonc-dev** [comment]
It looks like it works in a development environment. Quick few questions, do I need to run a update commands or install commands in Vercel?

Thanks!

**Comment by nekusu** [comment]
The default installation commands executed during deployment on Vercel should be enough. If it's working in your development environment with the same environment variables, the issue likely lies with the variables set in Vercel. Make sure that you don't include any quotation marks (`"`/`'`) or explicit line breaks (`\n`) in the string.

Also, the private key should begin with `-----BEGIN PRIVATE KEY-----` and end with `-----END PRIVATE KEY-----`.

Related: https://github.com/nodejs/help/issues/4115.

**Comment by masonc-dev** [comment]
Sorry to bother you with this issue again, but I have managed to change the error code I get when viewing user profiles :/ 
I now get the following error:
`Error: Only plain objects, and a few built-ins, can be passed to Client Components from Server Components. Classes or null prototypes are not supported.
    at /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:23954
    at Object.toJSON (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:25726)
    at stringify (<anonymous>)
    at eE (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:14115)
    at eR (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:14558)
    at Timeout._onTimeout (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:11338)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)`
I will continue to look for a fix for this, but I just wanted to ask if you have any idea how to fix this? 

Thanks again for all your help

**Comment by nekusu** [comment]
No problem at all, I'm glad to help. It's great to see that you've resolved the previous error, this one is much easier to tackle. As the error suggests, the error arises when attempting to pass classes from a server component to a client component, as Next.js itself can't serialize them.

In [app/user/[id]/page.tsx](https://github.com/nekusu/apetype/blob/eb894840283a13f77659bdfafc6fb0c8f16a73e0/app/user/%5Bid%5D/page.tsx), the User object contains three Firebase Timestamp objects parsed by the `getCollection` and `getDoc` functions using the `parseDates` parameter. Additionally, each Firebase document retrieved from a hook/function of the swr-firestore library includes a `ref` property that can't be serialized. To address this, I've destructured the User object, eliminating the `ref` property, and parsed the timestamps of `personalBests` using another function.

My current solution isn't perfect, in more recent commits I added a new library called [superjson](https://github.com/blitz-js/superjson), which, once I implement it for this use case, would make this operation much cleaner. However, the existing solution should work. Double-check for any unserializable properties that might be passed to a client component. Also, check the [Firebase console](https://console.firebase.google.com/) for properties in your user documents that might differ from the [User interface](https://github.com/nekusu/apetype/blob/eb894840283a13f77659bdfafc6fb0c8f16a73e0/utils/user.ts#L37-L64).

**Comment by sahupratik30** [comment]
> Sorry to bother you with this issue again, but I have managed to change the error code I get when viewing user profiles :/ I now get the following error: `Error: Only plain objects, and a few built-ins, can be passed to Client Components from Server Components. Classes or null prototypes are not supported. at /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:23954 at Object.toJSON (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:25726) at stringify (<anonymous>) at eE (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:14115) at eR (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:14558) at Timeout._onTimeout (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:11338) at listOnTimeout (node:internal/timers:569:17) at process.processTimers (node:internal/timers:512:7)` I will continue to look for a fix for this, but I just wanted to ask if you have any idea how to fix this?
> 
> Thanks again for all your help

How did you get rid of this issue? I am also facing the same issue but the error does not go.

**Comment by sahupratik30** [comment]
Below is the error that I am getting in the vercel logs:-
Error occured while saving order: Error: 2 UNKNOWN: Getting metadata from plugin failed with error: error:1E08010C:DECODER routines::unsupported
    at callErrorFromStatus (/var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.<anonymous> (/var/task/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /var/task/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:227:29
    at /var/task/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at repeat (/var/task/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
    at /var/task/node_modules/google-gax/build/src/normalCalls/retries.js:118:13
    at OngoingCallPromise.call (/var/task/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call (/var/task/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at /var/task/node_modules/google-gax/build/src/createApiCall.js:84:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Caused by: Error
    at WriteBatch.commit (/var/task/node_modules/@google-cloud/firestore/build/src/write-batch.js:433:23)
    at DocumentReference.set (/var/task/node_modules/@google-cloud/firestore/build/src/reference.js:395:27)
    at saveOrder (/var/task/.next/server/app/api/webhook/route.js:115:116)
    at POST (/var/task/.next/server/app/api/webhook/route.js:135:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/.next/server/chunks/501.js:5169:37 {
  code: 2,
  details: 'Getting metadata from plugin failed with error: error:1E08010C:DECODER routines::unsupported',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}
